// Copyright 2023 doesntfazer (@doesntfazer)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once


#define SPI_SCK_PIN GP2
#define SPI_MOSI_PIN GP3
#define SPI_MISO_PIN GP0
//#define I2C_DRIVER I2CD1
//#define I2C1_SDA_PIN GP0
//#define I2C1_SCL_PIN GP1
#define POINTING_DEVICE_CS_PIN GP1
#define CIRQUE_PINNACLE_SPI_CS_PIN GP1
#define POINTING_DEVICE_ROTATION_180
#define CIRQUE_PINNACLE_DIAMETER_MM 35
#define CIRQUE_PINNACLE_CURVED_OVERLAY
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 4
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define VIAL_COMBO_ENTERIES 10
#define DYNAMIC_KEYMAP_LAYER_COUNT 15

#define VENDOR_ID 0xFEED
#define PRODUCT_ID 0x0000
#define VIAL_KEYBOARD_UID {0x41, 0xD5, 0x81, 0x67, 0x67, 0x75, 0x62, 0x0F}
